gui:
  language: en
  sidePanelWidth: 0.45
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 4
  showFileIcons: true
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - '#FABD2F'
      - bold
    inactiveBorderColor:
      - '#928374'
    searchingActiveBorderColor:
      - '#FABD2F'
      - bold
    optionsTextColor:
      - '#6c757c'
    selectedLineBgColor:
      - '#161819'
    inactiveViewSelectedLineBgColor:
      - '#242728'
      - bold
    cherryPickedCommitFgColor:
      - '#D3869B'
    cherryPickedCommitBgColor:
      - '#D3869B'
    markedBaseCommitFgColor:
      - '#D3869B'
    markedBaseCommitBgColor:
      - '#FABD2F'
    unstagedChangesColor:
      - '#E45842'
    defaultFgColor:
      - '#B6AB8F'

  branchColorPatterns:
    '^DEV':      '#B7B947'
    'main':      '#B7B947'
    'develop':   '#B7B947'
    '^feature/': '#B6AB8F'

  customIcons:
    filenames:
      ".githook":   {icon: "󰊢", color: "#A074B3"}
      # ".githook":   {icon: "󰊢", color: "#E45842"}
      # "config.yml": {icon: "󰒓", color: "#EA863A"}
      # "config.yml": {icon: "󰒓", color: "#A074B3"}
    extensions:
      ".aac":    {icon: "", color: "#B8BB26"}
      ".bat":    {icon: "󰖳", color: "#B6AB8F"}
      ".bin":    {icon: "", color: "#B6AB8F"}
      ".c":      {icon: "", color: "#89A398"}
      ".css":    {icon: "", color: "#B6AB8F"}
      ".csv":    {icon: "󰓫", color: "#8EC07C"}
      ".cpp":    {icon: "", color: "#89A398"}
      ".html":   {icon: "", color: "#FE8019"}
      ".import": {icon: "", color: "#B6AB8F"}
      ".js":     {icon: "", color: "#EDBD50"}
      ".jsx":    {icon: "", color: "#EDBD50"}
      ".json":   {icon: "", color: "#B8BB26"}
      ".jpg":    {icon: "", color: "#B8BB26"}
      ".jpeg":   {icon: "", color: "#B8BB26"}
      ".lua":    {icon: "󰽥", color: "#C37D90"}
      ".md":     {icon: "", color: "#FE8019"}
      ".meta":   {icon: "", color: "#B6AB8F"}
      ".mp3":    {icon: "", color: "#B8BB26"}
      ".rs":     {icon: "", color: "#FE8019"}
      ".sh":     {icon: "", color: "#EDBD50"}
      ".toml":   {icon: "", color: "#A074B3"}
      ".ttf":    {icon: "", color: "#A074B3"}
      ".png":    {icon: "", color: "#B8BB26"}
      ".py":     {icon: "", color: "#B8BB26"}
      ".wav":    {icon: "", color: "#B8BB26"}
      ".webp":   {icon: "", color: "#B8BB26"}
      ".xml":    {icon: "󰗀", color: "#B6AB8F"}
      ".yml":    {icon: "", color: "#A074B3"}
      ".yaml":   {icon: "", color: "#A074B3"}

  authorColors:
    # 'DehKaine': '#B7B947'
    'DehKaine': '#83A598'
    '*': '#B7B947'

git:
  commit:
    autoWrapCommitMessage: true

keybinding:
  universal:
    return: <esc>
    prevTab: 'H'
    nextTab: 'L'
    nextScreenMode: '*'
    prevScreenMode: '#'

    prevBlock: 'K'
    nextBlock: 'J'
    prevBlock-alt: ''
    nextBlock-alt: ''
    prevBlock-alt2: ''
    nextBlock-alt2: ''

    scrollLeft: '<'
    scrollRight: '>'
    scrollUpMain-alt2: ''
    scrollDownMain-alt2: ''
    gotoTop: '^'
    gotoBottom: '$'

    goInto: 'l'
    # select: 'w'
    focusMainView: <tab>
    filteringMenu: <c-f>

    diffingMenu: <c-d>
    diffingMenu-alt: ''

  files:
    findBaseCommitForFixup: ''
    commitChangesWithoutHook: ''
    expandAll: '+'

  commits:
    openLogMenu: <c-s>
