gui:
  language: en
  sidePanelWidth: 0.45
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 4
  showFileIcons: true
  theme:
    activeBorderColor:
      - '#B7B947'
      - bold
    inactiveBorderColor:
      - '#928374'
    searchingActiveBorderColor:
      - '#FABD2F'
      - bold
    optionsTextColor:
      - '#6c757c'
    selectedLineBgColor:
      - '#161819'
    inactiveViewSelectedLineBgColor:
      - '#242728'
      - bold
    cherryPickedCommitFgColor:
      - '#D3869B'
    cherryPickedCommitBgColor:
      - '#D3869B'
    markedBaseCommitFgColor:
      - '#D3869B'
    markedBaseCommitBgColor:
      - '#FABD2F'
    unstagedChangesColor:
      - '#E45842'
    defaultFgColor:
      - '#B6AB8F'

  branchColorPatterns:
    '^DEV': '#B7B947'
    'main': '#B7B947'
    'develop': '#B7B947'
    '^feature/': '#B6AB8F'

  authorColors:
    'Dean': '#89A398'
    '*': '#85B0AA'

git:
  commit:
    autoWrapCommitMessage: true

keybinding:
  universal:
    return: <esc>
    prevTab: 'H'
    nextTab: 'L'
    nextScreenMode: '*'
    prevScreenMode: '#'

    prevBlock: 'K'
    nextBlock: 'J'
    prevBlock-alt: ''
    nextBlock-alt: ''
    prevBlock-alt2: ''
    nextBlock-alt2: ''

    scrollLeft: '<'
    scrollRight: '>'
    scrollUpMain-alt2: ''
    scrollDownMain-alt2: ''
    gotoTop: '^'
    gotoBottom: '$'

    goInto: 'l'
    # select: 'w'
    focusMainView: <tab>
    filteringMenu: <c-f>

    diffingMenu: <c-d>
    diffingMenu-alt: ''

  files:
    findBaseCommitForFixup: ''
    commitChangesWithoutHook: ''
    expandAll: '+'

  commits:
    openLogMenu: <c-s>
